//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CoolMvcBlog.WeatherService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://www.webservicex.net", ConfigurationName="WeatherService.WeatherForecastSoap")]
    public interface WeatherForecastSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.webservicex.net/GetWeatherByZipCode", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        CoolMvcBlog.WeatherService.WeatherForecasts GetWeatherByZipCode(string ZipCode);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://www.webservicex.net/GetWeatherByZipCode", ReplyAction="*")]
        System.IAsyncResult BeginGetWeatherByZipCode(string ZipCode, System.AsyncCallback callback, object asyncState);
        
        CoolMvcBlog.WeatherService.WeatherForecasts EndGetWeatherByZipCode(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.webservicex.net/GetWeatherByPlaceName", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        CoolMvcBlog.WeatherService.WeatherForecasts GetWeatherByPlaceName(string PlaceName);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://www.webservicex.net/GetWeatherByPlaceName", ReplyAction="*")]
        System.IAsyncResult BeginGetWeatherByPlaceName(string PlaceName, System.AsyncCallback callback, object asyncState);
        
        CoolMvcBlog.WeatherService.WeatherForecasts EndGetWeatherByPlaceName(System.IAsyncResult result);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.webservicex.net")]
    public partial class WeatherForecasts : object, System.ComponentModel.INotifyPropertyChanged {
        
        private float latitudeField;
        
        private float longitudeField;
        
        private float allocationFactorField;
        
        private string fipsCodeField;
        
        private string placeNameField;
        
        private string stateCodeField;
        
        private string statusField;
        
        private WeatherData[] detailsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public float Latitude {
            get {
                return this.latitudeField;
            }
            set {
                this.latitudeField = value;
                this.RaisePropertyChanged("Latitude");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public float Longitude {
            get {
                return this.longitudeField;
            }
            set {
                this.longitudeField = value;
                this.RaisePropertyChanged("Longitude");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public float AllocationFactor {
            get {
                return this.allocationFactorField;
            }
            set {
                this.allocationFactorField = value;
                this.RaisePropertyChanged("AllocationFactor");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string FipsCode {
            get {
                return this.fipsCodeField;
            }
            set {
                this.fipsCodeField = value;
                this.RaisePropertyChanged("FipsCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string PlaceName {
            get {
                return this.placeNameField;
            }
            set {
                this.placeNameField = value;
                this.RaisePropertyChanged("PlaceName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string StateCode {
            get {
                return this.stateCodeField;
            }
            set {
                this.stateCodeField = value;
                this.RaisePropertyChanged("StateCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string Status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
                this.RaisePropertyChanged("Status");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=7)]
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public WeatherData[] Details {
            get {
                return this.detailsField;
            }
            set {
                this.detailsField = value;
                this.RaisePropertyChanged("Details");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.webservicex.net")]
    public partial class WeatherData : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string dayField;
        
        private string weatherImageField;
        
        private string maxTemperatureFField;
        
        private string minTemperatureFField;
        
        private string maxTemperatureCField;
        
        private string minTemperatureCField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Day {
            get {
                return this.dayField;
            }
            set {
                this.dayField = value;
                this.RaisePropertyChanged("Day");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string WeatherImage {
            get {
                return this.weatherImageField;
            }
            set {
                this.weatherImageField = value;
                this.RaisePropertyChanged("WeatherImage");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string MaxTemperatureF {
            get {
                return this.maxTemperatureFField;
            }
            set {
                this.maxTemperatureFField = value;
                this.RaisePropertyChanged("MaxTemperatureF");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string MinTemperatureF {
            get {
                return this.minTemperatureFField;
            }
            set {
                this.minTemperatureFField = value;
                this.RaisePropertyChanged("MinTemperatureF");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string MaxTemperatureC {
            get {
                return this.maxTemperatureCField;
            }
            set {
                this.maxTemperatureCField = value;
                this.RaisePropertyChanged("MaxTemperatureC");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string MinTemperatureC {
            get {
                return this.minTemperatureCField;
            }
            set {
                this.minTemperatureCField = value;
                this.RaisePropertyChanged("MinTemperatureC");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WeatherForecastSoapChannel : CoolMvcBlog.WeatherService.WeatherForecastSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GetWeatherByZipCodeCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public GetWeatherByZipCodeCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public CoolMvcBlog.WeatherService.WeatherForecasts Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((CoolMvcBlog.WeatherService.WeatherForecasts)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GetWeatherByPlaceNameCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public GetWeatherByPlaceNameCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public CoolMvcBlog.WeatherService.WeatherForecasts Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((CoolMvcBlog.WeatherService.WeatherForecasts)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WeatherForecastSoapClient : System.ServiceModel.ClientBase<CoolMvcBlog.WeatherService.WeatherForecastSoap>, CoolMvcBlog.WeatherService.WeatherForecastSoap {
        
        private BeginOperationDelegate onBeginGetWeatherByZipCodeDelegate;
        
        private EndOperationDelegate onEndGetWeatherByZipCodeDelegate;
        
        private System.Threading.SendOrPostCallback onGetWeatherByZipCodeCompletedDelegate;
        
        private BeginOperationDelegate onBeginGetWeatherByPlaceNameDelegate;
        
        private EndOperationDelegate onEndGetWeatherByPlaceNameDelegate;
        
        private System.Threading.SendOrPostCallback onGetWeatherByPlaceNameCompletedDelegate;
        
        public WeatherForecastSoapClient() {
        }
        
        public WeatherForecastSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WeatherForecastSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WeatherForecastSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WeatherForecastSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public event System.EventHandler<GetWeatherByZipCodeCompletedEventArgs> GetWeatherByZipCodeCompleted;
        
        public event System.EventHandler<GetWeatherByPlaceNameCompletedEventArgs> GetWeatherByPlaceNameCompleted;
        
        public CoolMvcBlog.WeatherService.WeatherForecasts GetWeatherByZipCode(string ZipCode) {
            return base.Channel.GetWeatherByZipCode(ZipCode);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public System.IAsyncResult BeginGetWeatherByZipCode(string ZipCode, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginGetWeatherByZipCode(ZipCode, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public CoolMvcBlog.WeatherService.WeatherForecasts EndGetWeatherByZipCode(System.IAsyncResult result) {
            return base.Channel.EndGetWeatherByZipCode(result);
        }
        
        private System.IAsyncResult OnBeginGetWeatherByZipCode(object[] inValues, System.AsyncCallback callback, object asyncState) {
            string ZipCode = ((string)(inValues[0]));
            return this.BeginGetWeatherByZipCode(ZipCode, callback, asyncState);
        }
        
        private object[] OnEndGetWeatherByZipCode(System.IAsyncResult result) {
            CoolMvcBlog.WeatherService.WeatherForecasts retVal = this.EndGetWeatherByZipCode(result);
            return new object[] {
                    retVal};
        }
        
        private void OnGetWeatherByZipCodeCompleted(object state) {
            if ((this.GetWeatherByZipCodeCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.GetWeatherByZipCodeCompleted(this, new GetWeatherByZipCodeCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void GetWeatherByZipCodeAsync(string ZipCode) {
            this.GetWeatherByZipCodeAsync(ZipCode, null);
        }
        
        public void GetWeatherByZipCodeAsync(string ZipCode, object userState) {
            if ((this.onBeginGetWeatherByZipCodeDelegate == null)) {
                this.onBeginGetWeatherByZipCodeDelegate = new BeginOperationDelegate(this.OnBeginGetWeatherByZipCode);
            }
            if ((this.onEndGetWeatherByZipCodeDelegate == null)) {
                this.onEndGetWeatherByZipCodeDelegate = new EndOperationDelegate(this.OnEndGetWeatherByZipCode);
            }
            if ((this.onGetWeatherByZipCodeCompletedDelegate == null)) {
                this.onGetWeatherByZipCodeCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnGetWeatherByZipCodeCompleted);
            }
            base.InvokeAsync(this.onBeginGetWeatherByZipCodeDelegate, new object[] {
                        ZipCode}, this.onEndGetWeatherByZipCodeDelegate, this.onGetWeatherByZipCodeCompletedDelegate, userState);
        }
        
        public CoolMvcBlog.WeatherService.WeatherForecasts GetWeatherByPlaceName(string PlaceName) {
            return base.Channel.GetWeatherByPlaceName(PlaceName);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public System.IAsyncResult BeginGetWeatherByPlaceName(string PlaceName, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginGetWeatherByPlaceName(PlaceName, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public CoolMvcBlog.WeatherService.WeatherForecasts EndGetWeatherByPlaceName(System.IAsyncResult result) {
            return base.Channel.EndGetWeatherByPlaceName(result);
        }
        
        private System.IAsyncResult OnBeginGetWeatherByPlaceName(object[] inValues, System.AsyncCallback callback, object asyncState) {
            string PlaceName = ((string)(inValues[0]));
            return this.BeginGetWeatherByPlaceName(PlaceName, callback, asyncState);
        }
        
        private object[] OnEndGetWeatherByPlaceName(System.IAsyncResult result) {
            CoolMvcBlog.WeatherService.WeatherForecasts retVal = this.EndGetWeatherByPlaceName(result);
            return new object[] {
                    retVal};
        }
        
        private void OnGetWeatherByPlaceNameCompleted(object state) {
            if ((this.GetWeatherByPlaceNameCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.GetWeatherByPlaceNameCompleted(this, new GetWeatherByPlaceNameCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void GetWeatherByPlaceNameAsync(string PlaceName) {
            this.GetWeatherByPlaceNameAsync(PlaceName, null);
        }
        
        public void GetWeatherByPlaceNameAsync(string PlaceName, object userState) {
            if ((this.onBeginGetWeatherByPlaceNameDelegate == null)) {
                this.onBeginGetWeatherByPlaceNameDelegate = new BeginOperationDelegate(this.OnBeginGetWeatherByPlaceName);
            }
            if ((this.onEndGetWeatherByPlaceNameDelegate == null)) {
                this.onEndGetWeatherByPlaceNameDelegate = new EndOperationDelegate(this.OnEndGetWeatherByPlaceName);
            }
            if ((this.onGetWeatherByPlaceNameCompletedDelegate == null)) {
                this.onGetWeatherByPlaceNameCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnGetWeatherByPlaceNameCompleted);
            }
            base.InvokeAsync(this.onBeginGetWeatherByPlaceNameDelegate, new object[] {
                        PlaceName}, this.onEndGetWeatherByPlaceNameDelegate, this.onGetWeatherByPlaceNameCompletedDelegate, userState);
        }
    }
}
