//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.4016
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::System.Data.Objects.DataClasses.EdmSchemaAttribute()]

// Original file name:
// Generation date: 30/06/2009 12:06:26
namespace VirtualFileSystemModel
{
    
    /// <summary>
    /// There are no comments for VirtualFileSystemEntities in the schema.
    /// </summary>
    public partial class VirtualFileSystemEntities : global::System.Data.Objects.ObjectContext
    {
        /// <summary>
        /// Initializes a new VirtualFileSystemEntities object using the connection string found in the 'VirtualFileSystemEntities' section of the application configuration file.
        /// </summary>
        public VirtualFileSystemEntities() : 
                base("name=VirtualFileSystemEntities", "VirtualFileSystemEntities")
        {
            this.OnContextCreated();
        }
        /// <summary>
        /// Initialize a new VirtualFileSystemEntities object.
        /// </summary>
        public VirtualFileSystemEntities(string connectionString) : 
                base(connectionString, "VirtualFileSystemEntities")
        {
            this.OnContextCreated();
        }
        /// <summary>
        /// Initialize a new VirtualFileSystemEntities object.
        /// </summary>
        public VirtualFileSystemEntities(global::System.Data.EntityClient.EntityConnection connection) : 
                base(connection, "VirtualFileSystemEntities")
        {
            this.OnContextCreated();
        }
        partial void OnContextCreated();
        /// <summary>
        /// There are no comments for VirtualFiles in the schema.
        /// </summary>
        public global::System.Data.Objects.ObjectQuery<VirtualFiles> VirtualFiles
        {
            get
            {
                if ((this._VirtualFiles == null))
                {
                    this._VirtualFiles = base.CreateQuery<VirtualFiles>("[VirtualFiles]");
                }
                return this._VirtualFiles;
            }
        }
        private global::System.Data.Objects.ObjectQuery<VirtualFiles> _VirtualFiles;
        /// <summary>
        /// There are no comments for VirtualFiles in the schema.
        /// </summary>
        public void AddToVirtualFiles(VirtualFiles virtualFiles)
        {
            base.AddObject("VirtualFiles", virtualFiles);
        }
    }
    /// <summary>
    /// There are no comments for VirtualFileSystemModel.VirtualFiles in the schema.
    /// </summary>
    /// <KeyProperties>
    /// ID
    /// </KeyProperties>
    [global::System.Data.Objects.DataClasses.EdmEntityTypeAttribute(NamespaceName="VirtualFileSystemModel", Name="VirtualFiles")]
    [global::System.Runtime.Serialization.DataContractAttribute(IsReference=true)]
    [global::System.Serializable()]
    public partial class VirtualFiles : global::System.Data.Objects.DataClasses.EntityObject
    {
        /// <summary>
        /// Create a new VirtualFiles object.
        /// </summary>
        /// <param name="id">Initial value of ID.</param>
        /// <param name="virtualPath">Initial value of VirtualPath.</param>
        /// <param name="contents">Initial value of Contents.</param>
        /// <param name="lastUpdated">Initial value of LastUpdated.</param>
        public static VirtualFiles CreateVirtualFiles(int id, string virtualPath, string contents, byte[] lastUpdated)
        {
            VirtualFiles virtualFiles = new VirtualFiles();
            virtualFiles.ID = id;
            virtualFiles.VirtualPath = virtualPath;
            virtualFiles.Contents = contents;
            virtualFiles.LastUpdated = lastUpdated;
            return virtualFiles;
        }
        /// <summary>
        /// There are no comments for Property ID in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public int ID
        {
            get
            {
                return this._ID;
            }
            set
            {
                this.OnIDChanging(value);
                this.ReportPropertyChanging("ID");
                this._ID = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("ID");
                this.OnIDChanged();
            }
        }
        private int _ID;
        partial void OnIDChanging(int value);
        partial void OnIDChanged();
        /// <summary>
        /// There are no comments for Property VirtualPath in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string VirtualPath
        {
            get
            {
                return this._VirtualPath;
            }
            set
            {
                this.OnVirtualPathChanging(value);
                this.ReportPropertyChanging("VirtualPath");
                this._VirtualPath = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false);
                this.ReportPropertyChanged("VirtualPath");
                this.OnVirtualPathChanged();
            }
        }
        private string _VirtualPath;
        partial void OnVirtualPathChanging(string value);
        partial void OnVirtualPathChanged();
        /// <summary>
        /// There are no comments for Property Contents in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string Contents
        {
            get
            {
                return this._Contents;
            }
            set
            {
                this.OnContentsChanging(value);
                this.ReportPropertyChanging("Contents");
                this._Contents = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false);
                this.ReportPropertyChanged("Contents");
                this.OnContentsChanged();
            }
        }
        private string _Contents;
        partial void OnContentsChanging(string value);
        partial void OnContentsChanged();
        /// <summary>
        /// There are no comments for Property LastUpdated in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public byte[] LastUpdated
        {
            get
            {
                return global::System.Data.Objects.DataClasses.StructuralObject.GetValidValue(this._LastUpdated);
            }
            set
            {
                this.OnLastUpdatedChanging(value);
                this.ReportPropertyChanging("LastUpdated");
                this._LastUpdated = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false);
                this.ReportPropertyChanged("LastUpdated");
                this.OnLastUpdatedChanged();
            }
        }
        private byte[] _LastUpdated;
        partial void OnLastUpdatedChanging(byte[] value);
        partial void OnLastUpdatedChanged();
    }
}
