
'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated from a template.
'
'    Manual changes to this file may cause unexpected behavior in your application.
'    Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Data.Objects
Imports System.Data.Objects.DataClasses
Imports System.Data.EntityClient
Imports System.ComponentModel
Imports System.Xml.Serialization
Imports System.Runtime.Serialization

<Assembly: EdmSchemaAttribute("197106b5-5d2f-43e1-9cec-7603d0442ef3")>
#Region "EDM Relationship Metadata"
<Assembly: EdmRelationshipAttribute("usersModel", "UsersInRoles", "Roles", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, GetType(ObjectModel.Role), "Users", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, GetType(ObjectModel.User))>

#End Region
Namespace ObjectModel
    
    #Region "Contexts"
    
    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    Public Partial Class UsersEntities
        Inherits ObjectContext
    
        #Region "Constructors"
    
        ''' <summary>
        ''' Initializes a new UsersEntities object using the connection string found in the 'UsersEntities' section of the application configuration file.
        ''' </summary>
        Public Sub New()
            MyBase.New("name=UsersEntities", "UsersEntities")
            OnContextCreated()
        End Sub
    
        ''' <summary>
        ''' Initialize a new UsersEntities object.
        ''' </summary>
        Public Sub New(ByVal connectionString As String)
            MyBase.New(connectionString, "UsersEntities")
            OnContextCreated()
        End Sub
    
        ''' <summary>
        ''' Initialize a new UsersEntities object.
        ''' </summary>
        Public Sub New(ByVal connection As EntityConnection)
            MyBase.New(connection, "UsersEntities")
            OnContextCreated()
        End Sub
    
        #End Region
    
        #Region "Partial Methods"
    
        Partial Private Sub OnContextCreated()
        End Sub
    
        #End Region
    
        #Region "ObjectSet Properties"
    
        ''' <summary>
        ''' No Metadata Documentation available.
        ''' </summary>
        Public ReadOnly Property RoleSet() As ObjectSet(Of Role)
            Get
                If (_RoleSet Is Nothing) Then
                    _RoleSet = MyBase.CreateObjectSet(Of Role)("RoleSet")
                End If
                Return _RoleSet
            End Get
        End Property
    
        Private _RoleSet As ObjectSet(Of Role)
    
        ''' <summary>
        ''' No Metadata Documentation available.
        ''' </summary>
        Public ReadOnly Property UserSet() As ObjectSet(Of User)
            Get
                If (_UserSet Is Nothing) Then
                    _UserSet = MyBase.CreateObjectSet(Of User)("UserSet")
                End If
                Return _UserSet
            End Get
        End Property
    
        Private _UserSet As ObjectSet(Of User)

        #End Region
        #Region "AddTo Methods"
    
        ''' <summary>
        ''' Deprecated Method for adding a new object to the RoleSet EntitySet. Consider using the .Add method of the associated ObjectSet(Of T) property instead.
        ''' </summary>
        Public Sub AddToRoleSet(ByVal role As Role)
            MyBase.AddObject("RoleSet", role)
        End Sub
    
        ''' <summary>
        ''' Deprecated Method for adding a new object to the UserSet EntitySet. Consider using the .Add method of the associated ObjectSet(Of T) property instead.
        ''' </summary>
        Public Sub AddToUserSet(ByVal user As User)
            MyBase.AddObject("UserSet", user)
        End Sub

        #End Region
    End Class

    #End Region
    #Region "Entities"
    
    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmEntityTypeAttribute(NamespaceName:="usersModel", Name:="Role")>
    <Serializable()>
    <DataContractAttribute(IsReference:=True)>
    Public Partial Class Role
        Inherits EntityObject
        #Region "Factory Method"
    
        ''' <summary>
        ''' Create a new Role object.
        ''' </summary>
        ''' <param name="id">Initial value of the ID property.</param>
        ''' <param name="roleName">Initial value of the RoleName property.</param>
        Public Shared Function CreateRole(id As Global.System.Int32, roleName As Global.System.String) As Role
            Dim role as Role = New Role
            role.ID = id
            role.RoleName = roleName
            Return role
        End Function

        #End Region
        #Region "Primitive Properties"
    
        ''' <summary>
        ''' No Metadata Documentation available.
        ''' </summary>
        <EdmScalarPropertyAttribute(EntityKeyProperty:=true, IsNullable:=false)>
        <DataMemberAttribute()>
        Public Property ID() As Global.System.Int32
            Get
                Return _ID
            End Get
            Set
                If (_ID <> Value) Then
                    OnIDChanging(value)
                    ReportPropertyChanging("ID")
                    _ID = StructuralObject.SetValidValue(value)
                    ReportPropertyChanged("ID")
                    OnIDChanged()
                End If
            End Set
        End Property
    
        Private _ID As Global.System.Int32
        Private Partial Sub OnIDChanging(value As Global.System.Int32)
        End Sub
    
        Private Partial Sub OnIDChanged()
        End Sub
    
        ''' <summary>
        ''' No Metadata Documentation available.
        ''' </summary>
        <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
        <DataMemberAttribute()>
        Public Property RoleName() As Global.System.String
            Get
                Return _RoleName
            End Get
            Set
                OnRoleNameChanging(value)
                ReportPropertyChanging("RoleName")
                _RoleName = StructuralObject.SetValidValue(value, false)
                ReportPropertyChanged("RoleName")
                OnRoleNameChanged()
            End Set
        End Property
    
        Private _RoleName As Global.System.String
        Private Partial Sub OnRoleNameChanging(value As Global.System.String)
        End Sub
    
        Private Partial Sub OnRoleNameChanged()
        End Sub

        #End Region
        #Region "Navigation Properties"
    
        ''' <summary>
        ''' No Metadata Documentation available.
        ''' </summary>
        <XmlIgnoreAttribute()>
        <SoapIgnoreAttribute()>
        <DataMemberAttribute()>
        <EdmRelationshipNavigationPropertyAttribute("usersModel", "UsersInRoles", "Users")>
         Public Property Users() As EntityCollection(Of User)
            Get
                Return CType(Me,IEntityWithRelationships).RelationshipManager.GetRelatedCollection(Of User)("usersModel.UsersInRoles", "Users")
            End Get
            Set
                If (Not value Is Nothing)
                    CType(Me, IEntityWithRelationships).RelationshipManager.InitializeRelatedCollection(Of User)("usersModel.UsersInRoles", "Users", value)
                End If
            End Set
        End Property

        #End Region
    End Class
    
    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmEntityTypeAttribute(NamespaceName:="usersModel", Name:="User")>
    <Serializable()>
    <DataContractAttribute(IsReference:=True)>
    Public Partial Class User
        Inherits EntityObject
        #Region "Factory Method"
    
        ''' <summary>
        ''' Create a new User object.
        ''' </summary>
        ''' <param name="id">Initial value of the ID property.</param>
        ''' <param name="username">Initial value of the Username property.</param>
        ''' <param name="password">Initial value of the Password property.</param>
        ''' <param name="email">Initial value of the Email property.</param>
        Public Shared Function CreateUser(id As Global.System.Int32, username As Global.System.String, password As Global.System.String, email As Global.System.String) As User
            Dim user as User = New User
            user.ID = id
            user.Username = username
            user.Password = password
            user.Email = email
            Return user
        End Function

        #End Region
        #Region "Primitive Properties"
    
        ''' <summary>
        ''' No Metadata Documentation available.
        ''' </summary>
        <EdmScalarPropertyAttribute(EntityKeyProperty:=true, IsNullable:=false)>
        <DataMemberAttribute()>
        Public Property ID() As Global.System.Int32
            Get
                Return _ID
            End Get
            Set
                If (_ID <> Value) Then
                    OnIDChanging(value)
                    ReportPropertyChanging("ID")
                    _ID = StructuralObject.SetValidValue(value)
                    ReportPropertyChanged("ID")
                    OnIDChanged()
                End If
            End Set
        End Property
    
        Private _ID As Global.System.Int32
        Private Partial Sub OnIDChanging(value As Global.System.Int32)
        End Sub
    
        Private Partial Sub OnIDChanged()
        End Sub
    
        ''' <summary>
        ''' No Metadata Documentation available.
        ''' </summary>
        <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
        <DataMemberAttribute()>
        Public Property Username() As Global.System.String
            Get
                Return _Username
            End Get
            Set
                OnUsernameChanging(value)
                ReportPropertyChanging("Username")
                _Username = StructuralObject.SetValidValue(value, false)
                ReportPropertyChanged("Username")
                OnUsernameChanged()
            End Set
        End Property
    
        Private _Username As Global.System.String
        Private Partial Sub OnUsernameChanging(value As Global.System.String)
        End Sub
    
        Private Partial Sub OnUsernameChanged()
        End Sub
    
        ''' <summary>
        ''' No Metadata Documentation available.
        ''' </summary>
        <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
        <DataMemberAttribute()>
        Public Property Password() As Global.System.String
            Get
                Return _Password
            End Get
            Set
                OnPasswordChanging(value)
                ReportPropertyChanging("Password")
                _Password = StructuralObject.SetValidValue(value, false)
                ReportPropertyChanged("Password")
                OnPasswordChanged()
            End Set
        End Property
    
        Private _Password As Global.System.String
        Private Partial Sub OnPasswordChanging(value As Global.System.String)
        End Sub
    
        Private Partial Sub OnPasswordChanged()
        End Sub
    
        ''' <summary>
        ''' No Metadata Documentation available.
        ''' </summary>
        <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
        <DataMemberAttribute()>
        Public Property Email() As Global.System.String
            Get
                Return _Email
            End Get
            Set
                OnEmailChanging(value)
                ReportPropertyChanging("Email")
                _Email = StructuralObject.SetValidValue(value, false)
                ReportPropertyChanged("Email")
                OnEmailChanged()
            End Set
        End Property
    
        Private _Email As Global.System.String
        Private Partial Sub OnEmailChanging(value As Global.System.String)
        End Sub
    
        Private Partial Sub OnEmailChanged()
        End Sub

        #End Region
        #Region "Navigation Properties"
    
        ''' <summary>
        ''' No Metadata Documentation available.
        ''' </summary>
        <XmlIgnoreAttribute()>
        <SoapIgnoreAttribute()>
        <DataMemberAttribute()>
        <EdmRelationshipNavigationPropertyAttribute("usersModel", "UsersInRoles", "Roles")>
         Public Property Roles() As EntityCollection(Of Role)
            Get
                Return CType(Me,IEntityWithRelationships).RelationshipManager.GetRelatedCollection(Of Role)("usersModel.UsersInRoles", "Roles")
            End Get
            Set
                If (Not value Is Nothing)
                    CType(Me, IEntityWithRelationships).RelationshipManager.InitializeRelatedCollection(Of Role)("usersModel.UsersInRoles", "Roles", value)
                End If
            End Set
        End Property

        #End Region
    End Class

    #End Region
    
End Namespace
