
'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated from a template.
'
'    Manual changes to this file may cause unexpected behavior in your application.
'    Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Data.Objects
Imports System.Data.Objects.DataClasses
Imports System.Data.EntityClient
Imports System.ComponentModel
Imports System.Xml.Serialization
Imports System.Runtime.Serialization

<Assembly: EdmSchemaAttribute("5ab2f1a3-406a-409a-896d-e921b3d2fe33")>
Namespace VirtualFileSystemModel
    
    #Region "Contexts"
    
    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    Public Partial Class VirtualFileSystemEntities
        Inherits ObjectContext
    
        #Region "Constructors"
    
        ''' <summary>
        ''' Initializes a new VirtualFileSystemEntities object using the connection string found in the 'VirtualFileSystemEntities' section of the application configuration file.
        ''' </summary>
        Public Sub New()
            MyBase.New("name=VirtualFileSystemEntities", "VirtualFileSystemEntities")
            OnContextCreated()
        End Sub
    
        ''' <summary>
        ''' Initialize a new VirtualFileSystemEntities object.
        ''' </summary>
        Public Sub New(ByVal connectionString As String)
            MyBase.New(connectionString, "VirtualFileSystemEntities")
            OnContextCreated()
        End Sub
    
        ''' <summary>
        ''' Initialize a new VirtualFileSystemEntities object.
        ''' </summary>
        Public Sub New(ByVal connection As EntityConnection)
            MyBase.New(connection, "VirtualFileSystemEntities")
            OnContextCreated()
        End Sub
    
        #End Region
    
        #Region "Partial Methods"
    
        Partial Private Sub OnContextCreated()
        End Sub
    
        #End Region
    
        #Region "ObjectSet Properties"
    
        ''' <summary>
        ''' No Metadata Documentation available.
        ''' </summary>
        Public ReadOnly Property VirtualFiles() As ObjectSet(Of VirtualFiles)
            Get
                If (_VirtualFiles Is Nothing) Then
                    _VirtualFiles = MyBase.CreateObjectSet(Of VirtualFiles)("VirtualFiles")
                End If
                Return _VirtualFiles
            End Get
        End Property
    
        Private _VirtualFiles As ObjectSet(Of VirtualFiles)

        #End Region
        #Region "AddTo Methods"
    
        ''' <summary>
        ''' Deprecated Method for adding a new object to the VirtualFiles EntitySet. Consider using the .Add method of the associated ObjectSet(Of T) property instead.
        ''' </summary>
        Public Sub AddToVirtualFiles(ByVal virtualFiles As VirtualFiles)
            MyBase.AddObject("VirtualFiles", virtualFiles)
        End Sub

        #End Region
    End Class

    #End Region
    #Region "Entities"
    
    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmEntityTypeAttribute(NamespaceName:="VirtualFileSystemModel", Name:="VirtualFiles")>
    <Serializable()>
    <DataContractAttribute(IsReference:=True)>
    Public Partial Class VirtualFiles
        Inherits EntityObject
        #Region "Factory Method"
    
        ''' <summary>
        ''' Create a new VirtualFiles object.
        ''' </summary>
        ''' <param name="id">Initial value of the ID property.</param>
        ''' <param name="virtualPath">Initial value of the VirtualPath property.</param>
        ''' <param name="contents">Initial value of the Contents property.</param>
        ''' <param name="lastUpdated">Initial value of the LastUpdated property.</param>
        Public Shared Function CreateVirtualFiles(id As Global.System.Int32, virtualPath As Global.System.String, contents As Global.System.String, lastUpdated As Global.System.Byte()) As VirtualFiles
            Dim virtualFiles as VirtualFiles = New VirtualFiles
            virtualFiles.ID = id
            virtualFiles.VirtualPath = virtualPath
            virtualFiles.Contents = contents
            virtualFiles.LastUpdated = lastUpdated
            Return virtualFiles
        End Function

        #End Region
        #Region "Primitive Properties"
    
        ''' <summary>
        ''' No Metadata Documentation available.
        ''' </summary>
        <EdmScalarPropertyAttribute(EntityKeyProperty:=true, IsNullable:=false)>
        <DataMemberAttribute()>
        Public Property ID() As Global.System.Int32
            Get
                Return _ID
            End Get
            Set
                If (_ID <> Value) Then
                    OnIDChanging(value)
                    ReportPropertyChanging("ID")
                    _ID = StructuralObject.SetValidValue(value)
                    ReportPropertyChanged("ID")
                    OnIDChanged()
                End If
            End Set
        End Property
    
        Private _ID As Global.System.Int32
        Private Partial Sub OnIDChanging(value As Global.System.Int32)
        End Sub
    
        Private Partial Sub OnIDChanged()
        End Sub
    
        ''' <summary>
        ''' No Metadata Documentation available.
        ''' </summary>
        <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
        <DataMemberAttribute()>
        Public Property VirtualPath() As Global.System.String
            Get
                Return _VirtualPath
            End Get
            Set
                OnVirtualPathChanging(value)
                ReportPropertyChanging("VirtualPath")
                _VirtualPath = StructuralObject.SetValidValue(value, false)
                ReportPropertyChanged("VirtualPath")
                OnVirtualPathChanged()
            End Set
        End Property
    
        Private _VirtualPath As Global.System.String
        Private Partial Sub OnVirtualPathChanging(value As Global.System.String)
        End Sub
    
        Private Partial Sub OnVirtualPathChanged()
        End Sub
    
        ''' <summary>
        ''' No Metadata Documentation available.
        ''' </summary>
        <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
        <DataMemberAttribute()>
        Public Property Contents() As Global.System.String
            Get
                Return _Contents
            End Get
            Set
                OnContentsChanging(value)
                ReportPropertyChanging("Contents")
                _Contents = StructuralObject.SetValidValue(value, false)
                ReportPropertyChanged("Contents")
                OnContentsChanged()
            End Set
        End Property
    
        Private _Contents As Global.System.String
        Private Partial Sub OnContentsChanging(value As Global.System.String)
        End Sub
    
        Private Partial Sub OnContentsChanged()
        End Sub
    
        ''' <summary>
        ''' No Metadata Documentation available.
        ''' </summary>
        <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
        <DataMemberAttribute()>
        Public Property LastUpdated() As Global.System.Byte()
            Get
                    Return StructuralObject.GetValidValue(_LastUpdated)
            End Get
            Set
                OnLastUpdatedChanging(value)
                ReportPropertyChanging("LastUpdated")
                _LastUpdated = StructuralObject.SetValidValue(value, false)
                ReportPropertyChanged("LastUpdated")
                OnLastUpdatedChanged()
            End Set
        End Property
    
        Private _LastUpdated As Global.System.Byte()
        Private Partial Sub OnLastUpdatedChanging(value As Global.System.Byte())
        End Sub
    
        Private Partial Sub OnLastUpdatedChanged()
        End Sub

        #End Region
    End Class

    #End Region
    
End Namespace
