//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.4016
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::System.Data.Objects.DataClasses.EdmSchemaAttribute()]
[assembly: global::System.Data.Objects.DataClasses.EdmRelationshipAttribute("usersModel", "UsersInRoles", "Roles", global::System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(ObjectModel.Role), "Users", global::System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(ObjectModel.User))]

// Original file name:
// Generation date: 10/07/2009 21:04:25
namespace ObjectModel
{
    
    /// <summary>
    /// There are no comments for UsersEntities in the schema.
    /// </summary>
    public partial class UsersEntities : global::System.Data.Objects.ObjectContext
    {
        /// <summary>
        /// Initializes a new UsersEntities object using the connection string found in the 'UsersEntities' section of the application configuration file.
        /// </summary>
        public UsersEntities() : 
                base("name=UsersEntities", "UsersEntities")
        {
            this.OnContextCreated();
        }
        /// <summary>
        /// Initialize a new UsersEntities object.
        /// </summary>
        public UsersEntities(string connectionString) : 
                base(connectionString, "UsersEntities")
        {
            this.OnContextCreated();
        }
        /// <summary>
        /// Initialize a new UsersEntities object.
        /// </summary>
        public UsersEntities(global::System.Data.EntityClient.EntityConnection connection) : 
                base(connection, "UsersEntities")
        {
            this.OnContextCreated();
        }
        partial void OnContextCreated();
        /// <summary>
        /// There are no comments for RoleSet in the schema.
        /// </summary>
        public global::System.Data.Objects.ObjectQuery<Role> RoleSet
        {
            get
            {
                if ((this._RoleSet == null))
                {
                    this._RoleSet = base.CreateQuery<Role>("[RoleSet]");
                }
                return this._RoleSet;
            }
        }
        private global::System.Data.Objects.ObjectQuery<Role> _RoleSet;
        /// <summary>
        /// There are no comments for UserSet in the schema.
        /// </summary>
        public global::System.Data.Objects.ObjectQuery<User> UserSet
        {
            get
            {
                if ((this._UserSet == null))
                {
                    this._UserSet = base.CreateQuery<User>("[UserSet]");
                }
                return this._UserSet;
            }
        }
        private global::System.Data.Objects.ObjectQuery<User> _UserSet;
        /// <summary>
        /// There are no comments for RoleSet in the schema.
        /// </summary>
        public void AddToRoleSet(Role role)
        {
            base.AddObject("RoleSet", role);
        }
        /// <summary>
        /// There are no comments for UserSet in the schema.
        /// </summary>
        public void AddToUserSet(User user)
        {
            base.AddObject("UserSet", user);
        }
    }
    /// <summary>
    /// There are no comments for usersModel.Role in the schema.
    /// </summary>
    /// <KeyProperties>
    /// ID
    /// </KeyProperties>
    [global::System.Data.Objects.DataClasses.EdmEntityTypeAttribute(NamespaceName="usersModel", Name="Role")]
    [global::System.Runtime.Serialization.DataContractAttribute(IsReference=true)]
    [global::System.Serializable()]
    public partial class Role : global::System.Data.Objects.DataClasses.EntityObject
    {
        /// <summary>
        /// Create a new Role object.
        /// </summary>
        /// <param name="id">Initial value of ID.</param>
        /// <param name="roleName">Initial value of RoleName.</param>
        public static Role CreateRole(int id, string roleName)
        {
            Role role = new Role();
            role.ID = id;
            role.RoleName = roleName;
            return role;
        }
        /// <summary>
        /// There are no comments for Property ID in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public int ID
        {
            get
            {
                return this._ID;
            }
            set
            {
                this.OnIDChanging(value);
                this.ReportPropertyChanging("ID");
                this._ID = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("ID");
                this.OnIDChanged();
            }
        }
        private int _ID;
        partial void OnIDChanging(int value);
        partial void OnIDChanged();
        /// <summary>
        /// There are no comments for Property RoleName in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string RoleName
        {
            get
            {
                return this._RoleName;
            }
            set
            {
                this.OnRoleNameChanging(value);
                this.ReportPropertyChanging("RoleName");
                this._RoleName = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false);
                this.ReportPropertyChanged("RoleName");
                this.OnRoleNameChanged();
            }
        }
        private string _RoleName;
        partial void OnRoleNameChanging(string value);
        partial void OnRoleNameChanged();
        /// <summary>
        /// There are no comments for Users in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmRelationshipNavigationPropertyAttribute("usersModel", "UsersInRoles", "Users")]
        [global::System.Xml.Serialization.XmlIgnoreAttribute()]
        [global::System.Xml.Serialization.SoapIgnoreAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Data.Objects.DataClasses.EntityCollection<User> Users
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedCollection<User>("usersModel.UsersInRoles", "Users");
            }
            set
            {
                if ((value != null))
                {
                    ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.InitializeRelatedCollection<User>("usersModel.UsersInRoles", "Users", value);
                }
            }
        }
    }
    /// <summary>
    /// There are no comments for usersModel.User in the schema.
    /// </summary>
    /// <KeyProperties>
    /// ID
    /// </KeyProperties>
    [global::System.Data.Objects.DataClasses.EdmEntityTypeAttribute(NamespaceName="usersModel", Name="User")]
    [global::System.Runtime.Serialization.DataContractAttribute(IsReference=true)]
    [global::System.Serializable()]
    public partial class User : global::System.Data.Objects.DataClasses.EntityObject
    {
        /// <summary>
        /// Create a new User object.
        /// </summary>
        /// <param name="id">Initial value of ID.</param>
        /// <param name="username">Initial value of Username.</param>
        /// <param name="password">Initial value of Password.</param>
        /// <param name="email">Initial value of Email.</param>
        public static User CreateUser(int id, string username, string password, string email)
        {
            User user = new User();
            user.ID = id;
            user.Username = username;
            user.Password = password;
            user.Email = email;
            return user;
        }
        /// <summary>
        /// There are no comments for Property ID in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public int ID
        {
            get
            {
                return this._ID;
            }
            set
            {
                this.OnIDChanging(value);
                this.ReportPropertyChanging("ID");
                this._ID = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("ID");
                this.OnIDChanged();
            }
        }
        private int _ID;
        partial void OnIDChanging(int value);
        partial void OnIDChanged();
        /// <summary>
        /// There are no comments for Property Username in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string Username
        {
            get
            {
                return this._Username;
            }
            set
            {
                this.OnUsernameChanging(value);
                this.ReportPropertyChanging("Username");
                this._Username = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false);
                this.ReportPropertyChanged("Username");
                this.OnUsernameChanged();
            }
        }
        private string _Username;
        partial void OnUsernameChanging(string value);
        partial void OnUsernameChanged();
        /// <summary>
        /// There are no comments for Property Password in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string Password
        {
            get
            {
                return this._Password;
            }
            set
            {
                this.OnPasswordChanging(value);
                this.ReportPropertyChanging("Password");
                this._Password = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false);
                this.ReportPropertyChanged("Password");
                this.OnPasswordChanged();
            }
        }
        private string _Password;
        partial void OnPasswordChanging(string value);
        partial void OnPasswordChanged();
        /// <summary>
        /// There are no comments for Property Email in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string Email
        {
            get
            {
                return this._Email;
            }
            set
            {
                this.OnEmailChanging(value);
                this.ReportPropertyChanging("Email");
                this._Email = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false);
                this.ReportPropertyChanged("Email");
                this.OnEmailChanged();
            }
        }
        private string _Email;
        partial void OnEmailChanging(string value);
        partial void OnEmailChanged();
        /// <summary>
        /// There are no comments for Roles in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmRelationshipNavigationPropertyAttribute("usersModel", "UsersInRoles", "Roles")]
        [global::System.Xml.Serialization.XmlIgnoreAttribute()]
        [global::System.Xml.Serialization.SoapIgnoreAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Data.Objects.DataClasses.EntityCollection<Role> Roles
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedCollection<Role>("usersModel.UsersInRoles", "Roles");
            }
            set
            {
                if ((value != null))
                {
                    ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.InitializeRelatedCollection<Role>("usersModel.UsersInRoles", "Roles", value);
                }
            }
        }
    }
}
