
'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated from a template.
'
'    Manual changes to this file may cause unexpected behavior in your application.
'    Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Data.Objects
Imports System.Data.Objects.DataClasses
Imports System.Data.EntityClient
Imports System.ComponentModel
Imports System.Xml.Serialization
Imports System.Runtime.Serialization

<Assembly: EdmSchemaAttribute("817c65a3-7986-4fd0-b1f9-ea68d6eb8f2b")>
#Region "EDM Relationship Metadata"
<Assembly: EdmRelationshipAttribute("CoolMvcBlogModel", "FK_PostAuthor", "AuthorSet", System.Data.Metadata.Edm.RelationshipMultiplicity.One, GetType(Author), "PostSet", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, GetType(Post), True)>
<Assembly: EdmRelationshipAttribute("CoolMvcBlogModel", "FK_Comments_Posts", "PostSet", System.Data.Metadata.Edm.RelationshipMultiplicity.One, GetType(Post), "Comments", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, GetType(Comment), True)>
<Assembly: EdmRelationshipAttribute("CoolMvcBlogModel", "PostCategory", "CategorySet", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, GetType(Category), "PostSet", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, GetType(Post))>

#End Region

#Region "Contexts"

''' <summary>
''' No Metadata Documentation available.
''' </summary>
Public Partial Class BlogModelContainer
    Inherits ObjectContext

    #Region "Constructors"

    ''' <summary>
    ''' Initializes a new BlogModelContainer object using the connection string found in the 'BlogModelContainer' section of the application configuration file.
    ''' </summary>
    Public Sub New()
        MyBase.New("name=BlogModelContainer", "BlogModelContainer")
    MyBase.ContextOptions.LazyLoadingEnabled = true
        OnContextCreated()
    End Sub

    ''' <summary>
    ''' Initialize a new BlogModelContainer object.
    ''' </summary>
    Public Sub New(ByVal connectionString As String)
        MyBase.New(connectionString, "BlogModelContainer")
    MyBase.ContextOptions.LazyLoadingEnabled = true
        OnContextCreated()
    End Sub

    ''' <summary>
    ''' Initialize a new BlogModelContainer object.
    ''' </summary>
    Public Sub New(ByVal connection As EntityConnection)
        MyBase.New(connection, "BlogModelContainer")
    MyBase.ContextOptions.LazyLoadingEnabled = true
        OnContextCreated()
    End Sub

    #End Region

    #Region "Partial Methods"

    Partial Private Sub OnContextCreated()
    End Sub

    #End Region

    #Region "ObjectSet Properties"

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    Public ReadOnly Property AuthorSet() As ObjectSet(Of Author)
        Get
            If (_AuthorSet Is Nothing) Then
                _AuthorSet = MyBase.CreateObjectSet(Of Author)("AuthorSet")
            End If
            Return _AuthorSet
        End Get
    End Property

    Private _AuthorSet As ObjectSet(Of Author)

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    Public ReadOnly Property CategorySet() As ObjectSet(Of Category)
        Get
            If (_CategorySet Is Nothing) Then
                _CategorySet = MyBase.CreateObjectSet(Of Category)("CategorySet")
            End If
            Return _CategorySet
        End Get
    End Property

    Private _CategorySet As ObjectSet(Of Category)

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    Public ReadOnly Property CommentSet() As ObjectSet(Of Comment)
        Get
            If (_CommentSet Is Nothing) Then
                _CommentSet = MyBase.CreateObjectSet(Of Comment)("CommentSet")
            End If
            Return _CommentSet
        End Get
    End Property

    Private _CommentSet As ObjectSet(Of Comment)

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    Public ReadOnly Property PostSet() As ObjectSet(Of Post)
        Get
            If (_PostSet Is Nothing) Then
                _PostSet = MyBase.CreateObjectSet(Of Post)("PostSet")
            End If
            Return _PostSet
        End Get
    End Property

    Private _PostSet As ObjectSet(Of Post)

    #End Region
    #Region "AddTo Methods"

    ''' <summary>
    ''' Deprecated Method for adding a new object to the AuthorSet EntitySet. Consider using the .Add method of the associated ObjectSet(Of T) property instead.
    ''' </summary>
    Public Sub AddToAuthorSet(ByVal author As Author)
        MyBase.AddObject("AuthorSet", author)
    End Sub

    ''' <summary>
    ''' Deprecated Method for adding a new object to the CategorySet EntitySet. Consider using the .Add method of the associated ObjectSet(Of T) property instead.
    ''' </summary>
    Public Sub AddToCategorySet(ByVal category As Category)
        MyBase.AddObject("CategorySet", category)
    End Sub

    ''' <summary>
    ''' Deprecated Method for adding a new object to the CommentSet EntitySet. Consider using the .Add method of the associated ObjectSet(Of T) property instead.
    ''' </summary>
    Public Sub AddToCommentSet(ByVal comment As Comment)
        MyBase.AddObject("CommentSet", comment)
    End Sub

    ''' <summary>
    ''' Deprecated Method for adding a new object to the PostSet EntitySet. Consider using the .Add method of the associated ObjectSet(Of T) property instead.
    ''' </summary>
    Public Sub AddToPostSet(ByVal post As Post)
        MyBase.AddObject("PostSet", post)
    End Sub

    #End Region
End Class

#End Region
#Region "Entities"

''' <summary>
''' No Metadata Documentation available.
''' </summary>
<EdmEntityTypeAttribute(NamespaceName:="CoolMvcBlogModel", Name:="Author")>
<Serializable()>
<DataContractAttribute(IsReference:=True)>
Public Partial Class Author
    Inherits EntityObject
    #Region "Factory Method"

    ''' <summary>
    ''' Create a new Author object.
    ''' </summary>
    ''' <param name="id">Initial value of the Id property.</param>
    ''' <param name="name">Initial value of the Name property.</param>
    Public Shared Function CreateAuthor(id As Global.System.Int32, name As Global.System.String) As Author
        Dim author as Author = New Author
        author.Id = id
        author.Name = name
        Return author
    End Function

    #End Region
    #Region "Primitive Properties"

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=true, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property Id() As Global.System.Int32
        Get
            Return _Id
        End Get
        Set
            If (_Id <> Value) Then
                OnIdChanging(value)
                ReportPropertyChanging("Id")
                _Id = StructuralObject.SetValidValue(value)
                ReportPropertyChanged("Id")
                OnIdChanged()
            End If
        End Set
    End Property

    Private _Id As Global.System.Int32
    Private Partial Sub OnIdChanging(value As Global.System.Int32)
    End Sub

    Private Partial Sub OnIdChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property Name() As Global.System.String
        Get
            Return _Name
        End Get
        Set
            OnNameChanging(value)
            ReportPropertyChanging("Name")
            _Name = StructuralObject.SetValidValue(value, false)
            ReportPropertyChanged("Name")
            OnNameChanged()
        End Set
    End Property

    Private _Name As Global.System.String
    Private Partial Sub OnNameChanging(value As Global.System.String)
    End Sub

    Private Partial Sub OnNameChanged()
    End Sub

    #End Region
End Class

''' <summary>
''' No Metadata Documentation available.
''' </summary>
<EdmEntityTypeAttribute(NamespaceName:="CoolMvcBlogModel", Name:="Category")>
<Serializable()>
<DataContractAttribute(IsReference:=True)>
Public Partial Class Category
    Inherits EntityObject
    #Region "Factory Method"

    ''' <summary>
    ''' Create a new Category object.
    ''' </summary>
    ''' <param name="id">Initial value of the Id property.</param>
    ''' <param name="description">Initial value of the Description property.</param>
    Public Shared Function CreateCategory(id As Global.System.Int32, description As Global.System.String) As Category
        Dim category as Category = New Category
        category.Id = id
        category.Description = description
        Return category
    End Function

    #End Region
    #Region "Primitive Properties"

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=true, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property Id() As Global.System.Int32
        Get
            Return _Id
        End Get
        Set
            If (_Id <> Value) Then
                OnIdChanging(value)
                ReportPropertyChanging("Id")
                _Id = StructuralObject.SetValidValue(value)
                ReportPropertyChanged("Id")
                OnIdChanged()
            End If
        End Set
    End Property

    Private _Id As Global.System.Int32
    Private Partial Sub OnIdChanging(value As Global.System.Int32)
    End Sub

    Private Partial Sub OnIdChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property Description() As Global.System.String
        Get
            Return _Description
        End Get
        Set
            OnDescriptionChanging(value)
            ReportPropertyChanging("Description")
            _Description = StructuralObject.SetValidValue(value, false)
            ReportPropertyChanged("Description")
            OnDescriptionChanged()
        End Set
    End Property

    Private _Description As Global.System.String
    Private Partial Sub OnDescriptionChanging(value As Global.System.String)
    End Sub

    Private Partial Sub OnDescriptionChanged()
    End Sub

    #End Region
    #Region "Navigation Properties"

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <XmlIgnoreAttribute()>
    <SoapIgnoreAttribute()>
    <DataMemberAttribute()>
    <EdmRelationshipNavigationPropertyAttribute("CoolMvcBlogModel", "PostCategory", "PostSet")>
     Public Property Posts() As EntityCollection(Of Post)
        Get
            Return CType(Me,IEntityWithRelationships).RelationshipManager.GetRelatedCollection(Of Post)("CoolMvcBlogModel.PostCategory", "PostSet")
        End Get
        Set
            If (Not value Is Nothing)
                CType(Me, IEntityWithRelationships).RelationshipManager.InitializeRelatedCollection(Of Post)("CoolMvcBlogModel.PostCategory", "PostSet", value)
            End If
        End Set
    End Property

    #End Region
End Class

''' <summary>
''' No Metadata Documentation available.
''' </summary>
<EdmEntityTypeAttribute(NamespaceName:="CoolMvcBlogModel", Name:="Comment")>
<Serializable()>
<DataContractAttribute(IsReference:=True)>
Public Partial Class Comment
    Inherits EntityObject
    #Region "Factory Method"

    ''' <summary>
    ''' Create a new Comment object.
    ''' </summary>
    ''' <param name="id">Initial value of the Id property.</param>
    ''' <param name="date">Initial value of the Date property.</param>
    ''' <param name="author">Initial value of the Author property.</param>
    ''' <param name="email">Initial value of the Email property.</param>
    ''' <param name="text">Initial value of the Text property.</param>
    ''' <param name="postId">Initial value of the PostId property.</param>
    Public Shared Function CreateComment(id As Global.System.Int32, [date] As Global.System.DateTime, author As Global.System.String, email As Global.System.String, text As Global.System.String, postId As Global.System.Int32) As Comment
        Dim comment as Comment = New Comment
        comment.Id = id
        comment.[Date] = [date]
        comment.Author = author
        comment.Email = email
        comment.Text = text
        comment.PostId = postId
        Return comment
    End Function

    #End Region
    #Region "Primitive Properties"

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=true, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property Id() As Global.System.Int32
        Get
            Return _Id
        End Get
        Set
            If (_Id <> Value) Then
                OnIdChanging(value)
                ReportPropertyChanging("Id")
                _Id = StructuralObject.SetValidValue(value)
                ReportPropertyChanged("Id")
                OnIdChanged()
            End If
        End Set
    End Property

    Private _Id As Global.System.Int32
    Private Partial Sub OnIdChanging(value As Global.System.Int32)
    End Sub

    Private Partial Sub OnIdChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property [Date]() As Global.System.DateTime
        Get
            Return _Date
        End Get
        Set
            OnDateChanging(value)
            ReportPropertyChanging("Date")
            _Date = StructuralObject.SetValidValue(value)
            ReportPropertyChanged("Date")
            OnDateChanged()
        End Set
    End Property

    Private _Date As Global.System.DateTime
    Private Partial Sub OnDateChanging(value As Global.System.DateTime)
    End Sub

    Private Partial Sub OnDateChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property Author() As Global.System.String
        Get
            Return _Author
        End Get
        Set
            OnAuthorChanging(value)
            ReportPropertyChanging("Author")
            _Author = StructuralObject.SetValidValue(value, false)
            ReportPropertyChanged("Author")
            OnAuthorChanged()
        End Set
    End Property

    Private _Author As Global.System.String
    Private Partial Sub OnAuthorChanging(value As Global.System.String)
    End Sub

    Private Partial Sub OnAuthorChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property Email() As Global.System.String
        Get
            Return _Email
        End Get
        Set
            OnEmailChanging(value)
            ReportPropertyChanging("Email")
            _Email = StructuralObject.SetValidValue(value, false)
            ReportPropertyChanged("Email")
            OnEmailChanged()
        End Set
    End Property

    Private _Email As Global.System.String
    Private Partial Sub OnEmailChanging(value As Global.System.String)
    End Sub

    Private Partial Sub OnEmailChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property WebSite() As Global.System.String
        Get
            Return _WebSite
        End Get
        Set
            OnWebSiteChanging(value)
            ReportPropertyChanging("WebSite")
            _WebSite = StructuralObject.SetValidValue(value, true)
            ReportPropertyChanged("WebSite")
            OnWebSiteChanged()
        End Set
    End Property

    Private _WebSite As Global.System.String
    Private Partial Sub OnWebSiteChanging(value As Global.System.String)
    End Sub

    Private Partial Sub OnWebSiteChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property Text() As Global.System.String
        Get
            Return _Text
        End Get
        Set
            OnTextChanging(value)
            ReportPropertyChanging("Text")
            _Text = StructuralObject.SetValidValue(value, false)
            ReportPropertyChanged("Text")
            OnTextChanged()
        End Set
    End Property

    Private _Text As Global.System.String
    Private Partial Sub OnTextChanging(value As Global.System.String)
    End Sub

    Private Partial Sub OnTextChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property PostId() As Global.System.Int32
        Get
            Return _PostId
        End Get
        Set
            OnPostIdChanging(value)
            ReportPropertyChanging("PostId")
            _PostId = StructuralObject.SetValidValue(value)
            ReportPropertyChanged("PostId")
            OnPostIdChanged()
        End Set
    End Property

    Private _PostId As Global.System.Int32
    Private Partial Sub OnPostIdChanging(value As Global.System.Int32)
    End Sub

    Private Partial Sub OnPostIdChanged()
    End Sub

    #End Region
    #Region "Navigation Properties"

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <XmlIgnoreAttribute()>
    <SoapIgnoreAttribute()>
    <DataMemberAttribute()>
    <EdmRelationshipNavigationPropertyAttribute("CoolMvcBlogModel", "FK_Comments_Posts", "PostSet")>
    Public Property Post() As Post
        Get
            Return CType(Me, IEntityWithRelationships).RelationshipManager.GetRelatedReference(Of Post)("CoolMvcBlogModel.FK_Comments_Posts", "PostSet").Value
        End Get
        Set
            CType(Me, IEntityWithRelationships).RelationshipManager.GetRelatedReference(Of Post)("CoolMvcBlogModel.FK_Comments_Posts", "PostSet").Value = value
        End Set
    End Property
    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <BrowsableAttribute(False)>
    <DataMemberAttribute()>
    Public Property PostReference() As EntityReference(Of Post)
        Get
            Return CType(Me, IEntityWithRelationships).RelationshipManager.GetRelatedReference(Of Post)("CoolMvcBlogModel.FK_Comments_Posts", "PostSet")
        End Get
        Set
            If (Not value Is Nothing)
                CType(Me, IEntityWithRelationships).RelationshipManager.InitializeRelatedReference(Of Post)("CoolMvcBlogModel.FK_Comments_Posts", "PostSet", value)
            End If
        End Set
    End Property

    #End Region
End Class

''' <summary>
''' No Metadata Documentation available.
''' </summary>
<EdmEntityTypeAttribute(NamespaceName:="CoolMvcBlogModel", Name:="Post")>
<Serializable()>
<DataContractAttribute(IsReference:=True)>
Public Partial Class Post
    Inherits EntityObject
    #Region "Factory Method"

    ''' <summary>
    ''' Create a new Post object.
    ''' </summary>
    ''' <param name="id">Initial value of the Id property.</param>
    ''' <param name="authorId">Initial value of the AuthorId property.</param>
    ''' <param name="title">Initial value of the Title property.</param>
    ''' <param name="text">Initial value of the Text property.</param>
    ''' <param name="datePublished">Initial value of the DatePublished property.</param>
    Public Shared Function CreatePost(id As Global.System.Int32, authorId As Global.System.Int32, title As Global.System.String, text As Global.System.String, datePublished As Global.System.DateTime) As Post
        Dim post as Post = New Post
        post.Id = id
        post.AuthorId = authorId
        post.Title = title
        post.Text = text
        post.DatePublished = datePublished
        Return post
    End Function

    #End Region
    #Region "Primitive Properties"

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=true, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property Id() As Global.System.Int32
        Get
            Return _Id
        End Get
        Set
            If (_Id <> Value) Then
                OnIdChanging(value)
                ReportPropertyChanging("Id")
                _Id = StructuralObject.SetValidValue(value)
                ReportPropertyChanged("Id")
                OnIdChanged()
            End If
        End Set
    End Property

    Private _Id As Global.System.Int32
    Private Partial Sub OnIdChanging(value As Global.System.Int32)
    End Sub

    Private Partial Sub OnIdChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property AuthorId() As Global.System.Int32
        Get
            Return _AuthorId
        End Get
        Set
            OnAuthorIdChanging(value)
            ReportPropertyChanging("AuthorId")
            _AuthorId = StructuralObject.SetValidValue(value)
            ReportPropertyChanged("AuthorId")
            OnAuthorIdChanged()
        End Set
    End Property

    Private _AuthorId As Global.System.Int32
    Private Partial Sub OnAuthorIdChanging(value As Global.System.Int32)
    End Sub

    Private Partial Sub OnAuthorIdChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property Title() As Global.System.String
        Get
            Return _Title
        End Get
        Set
            OnTitleChanging(value)
            ReportPropertyChanging("Title")
            _Title = StructuralObject.SetValidValue(value, false)
            ReportPropertyChanged("Title")
            OnTitleChanged()
        End Set
    End Property

    Private _Title As Global.System.String
    Private Partial Sub OnTitleChanging(value As Global.System.String)
    End Sub

    Private Partial Sub OnTitleChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property Text() As Global.System.String
        Get
            Return _Text
        End Get
        Set
            OnTextChanging(value)
            ReportPropertyChanging("Text")
            _Text = StructuralObject.SetValidValue(value, false)
            ReportPropertyChanged("Text")
            OnTextChanged()
        End Set
    End Property

    Private _Text As Global.System.String
    Private Partial Sub OnTextChanging(value As Global.System.String)
    End Sub

    Private Partial Sub OnTextChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property DatePublished() As Global.System.DateTime
        Get
            Return _DatePublished
        End Get
        Set
            OnDatePublishedChanging(value)
            ReportPropertyChanging("DatePublished")
            _DatePublished = StructuralObject.SetValidValue(value)
            ReportPropertyChanged("DatePublished")
            OnDatePublishedChanged()
        End Set
    End Property

    Private _DatePublished As Global.System.DateTime
    Private Partial Sub OnDatePublishedChanging(value As Global.System.DateTime)
    End Sub

    Private Partial Sub OnDatePublishedChanged()
    End Sub

    #End Region
    #Region "Navigation Properties"

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <XmlIgnoreAttribute()>
    <SoapIgnoreAttribute()>
    <DataMemberAttribute()>
    <EdmRelationshipNavigationPropertyAttribute("CoolMvcBlogModel", "FK_PostAuthor", "AuthorSet")>
    Public Property Author() As Author
        Get
            Return CType(Me, IEntityWithRelationships).RelationshipManager.GetRelatedReference(Of Author)("CoolMvcBlogModel.FK_PostAuthor", "AuthorSet").Value
        End Get
        Set
            CType(Me, IEntityWithRelationships).RelationshipManager.GetRelatedReference(Of Author)("CoolMvcBlogModel.FK_PostAuthor", "AuthorSet").Value = value
        End Set
    End Property
    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <BrowsableAttribute(False)>
    <DataMemberAttribute()>
    Public Property AuthorReference() As EntityReference(Of Author)
        Get
            Return CType(Me, IEntityWithRelationships).RelationshipManager.GetRelatedReference(Of Author)("CoolMvcBlogModel.FK_PostAuthor", "AuthorSet")
        End Get
        Set
            If (Not value Is Nothing)
                CType(Me, IEntityWithRelationships).RelationshipManager.InitializeRelatedReference(Of Author)("CoolMvcBlogModel.FK_PostAuthor", "AuthorSet", value)
            End If
        End Set
    End Property

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <XmlIgnoreAttribute()>
    <SoapIgnoreAttribute()>
    <DataMemberAttribute()>
    <EdmRelationshipNavigationPropertyAttribute("CoolMvcBlogModel", "FK_Comments_Posts", "Comments")>
     Public Property Comments() As EntityCollection(Of Comment)
        Get
            Return CType(Me,IEntityWithRelationships).RelationshipManager.GetRelatedCollection(Of Comment)("CoolMvcBlogModel.FK_Comments_Posts", "Comments")
        End Get
        Set
            If (Not value Is Nothing)
                CType(Me, IEntityWithRelationships).RelationshipManager.InitializeRelatedCollection(Of Comment)("CoolMvcBlogModel.FK_Comments_Posts", "Comments", value)
            End If
        End Set
    End Property

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <XmlIgnoreAttribute()>
    <SoapIgnoreAttribute()>
    <DataMemberAttribute()>
    <EdmRelationshipNavigationPropertyAttribute("CoolMvcBlogModel", "PostCategory", "CategorySet")>
     Public Property Categories() As EntityCollection(Of Category)
        Get
            Return CType(Me,IEntityWithRelationships).RelationshipManager.GetRelatedCollection(Of Category)("CoolMvcBlogModel.PostCategory", "CategorySet")
        End Get
        Set
            If (Not value Is Nothing)
                CType(Me, IEntityWithRelationships).RelationshipManager.InitializeRelatedCollection(Of Category)("CoolMvcBlogModel.PostCategory", "CategorySet", value)
            End If
        End Set
    End Property

    #End Region
End Class

#End Region

